package failures;

public enum FailureType {
	// Pipe
	BLOCKED, LEAK,
	
	// Pump
	NO_PRESSURE, OVER_PRESSURED, 
	
	// ???
	ALLOWING_NO_PRESSURE, 
	
	// Valve
	STUCK, // LEAK,
	
	// Cylinder
	DISCONNECTED, // STUCK, LEAK
	
	// BSCU
	LOSS_OF_CONTROL_SIGNAL,
	
	// Contactor
	STUCK_OPEN, STUCK_CLOSED,
	
	// Generator
	REVERSE_CURRENT, OVER_VOLTAGE, LOSS_OF_POWER, UNDER_VOLTAGE,
	
	// Battery
	UNDER_CHARGED, // SHORT_CIRCUIT, 
	
	// Inventer ===> Same as generator
	// REVERSE_CURRENT, OVER_VOLTAGE, UNDER_VOLTAGE,
	 SHORT_CIRCUIT,
	
	// Electric wire
	BROKEN, CARRYING_REVERSE_CURRENT, CARRYING_HIGH_CURRENT,
	
	// Busbar
	FAILED_TO_CONDUCT, CONDUCTING_UNDER_VOLTAGE, CONDUCTING_OVER_VOLTAGE, // SHORT_CIRCUIT
	
	// DCConsumer same as generator + open circuit
	// REVERSE_CURRENT, OVER_VOLTAGE, UNDER_VOLTAGE, SHORT_CIRCUIT, 
	OPEN_CIRCUIT, NO_SUPPLY,
	
	// ACConsumer same as DCConsumer
	// REVERSE_CURRENT, OVER_VOLTAGE, UNDER_VOLTAGE, SHORT_CIRCUIT, OPEN_CIRCUIT
	
	// Diode
	// STUCK_CLOSED
	
	// Power Supply
	LOSS_OF_POWER_SUPPLY, 
	
	// ACE
	// LOSS_OF_POWER_SUPPLY, 
	LOSS_OR_INVALID_CONTROL_SIGNAL, LOSS_OF_INPUT_SIGNAL,
	
	// PFC
	// LOSS_OF_POWER_SUPPLY, LOSS_OR_INVALID_CONTROL_SIGNAL, LOSS_OF_INPUT_SIGNAL,
	
	// ADIRU
	 LOSS_OR_INVALID_OUTPUT_SIGNAL, // LOSS_OF_POWER_SUPPLY,	
	 
	 // Direct Electrical Link
	 LOSS_OF_ELECTRICAL_SIGNAL,
	 
	 // Control Rod
	 JAMMING, // DISCONNECTED
	 
	 // Engine
	 SURGE, STALL, FLAME_OUT, OVER_SPEED, OVER_TEMPERATURE, FUEL_SUPPLY_FAILURE,
	 
	 // Sensor
	 LOSS_OF_OUTPUT_SIGNAL, INVALID_OUTPUT_SIGNAL;
	 

}
