package components;

public enum ComponentType {
	CUSTOMIZED_COMPONENT, VALVE, PUMP, PIPE, PISTON, BSCU, CYLINDER,
	GENERATOR, ELECTRICWIRE, BUSBAR, INVERTER, DCCONSUMER, ACCONSUMER, CONTACTOR, BATTERY, DIODE,
	ACTUATOR_CONTROL_ELECTRONICS, PRIMARY_FLIGHT_CONTROL, AIR_DATA_AND_INERTIAL_REFERENCE_UNIT, POWER_SUPPLY,
	DIRECT_ELECTRICAL_LINK,
	CONTROL_ROD,
	ENGINE,
	SENSOR;
}
